create table if not exists classification_suggestions (
    row_id bigint generated by default as identity primary key,
    suggestion_id varchar(36) not null,
    connection_id uuid not null,
    tenant_id varchar(120) not null,
    user_id varchar(120) not null,
    message_id varchar(255) not null,
    thread_id varchar(255) not null,
    intent varchar(64) not null,
    direction varchar(32) not null,
    confidence double precision not null,
    requires_review boolean not null,
    classifier_version varchar(128) not null,
    content_hash varchar(128) not null,
    company_json text,
    role_json text,
    application_date_json text,
    contact_json text,
    evidence_json text not null,
    missing_fields_json text not null,
    contradictions_json text not null,
    created_at timestamp with time zone not null default current_timestamp,
    constraint ux_classification_suggestions_suggestion_id unique (suggestion_id),
    constraint ux_classification_suggestions_idempotency unique (
        tenant_id,
        user_id,
        connection_id,
        message_id,
        classifier_version,
        content_hash
    ),
    constraint fk_classification_suggestions_connection
        foreign key (connection_id) references gmail_connections(connection_id)
);

create index if not exists ix_classification_suggestions_latest
    on classification_suggestions (tenant_id, user_id, connection_id, message_id, created_at);
