package dev.jobflow.contacts;

public enum EnrichmentStatus { QUEUED, RUNNING, PUBLIC_SEARCH, GMAIL_SEARCH, PROVIDER_SEARCH, VERIFYING, READY, COMPLETED, NO_VERIFIED_CONTACT, FAILED, PROVIDER_UNAVAILABLE }
