import { createElement as h, useState, type ChangeEvent } from "react";

export type GmailReviewItem = { connectionId: string; suggestion: { suggestionId: string; messageId: string; threadId: string; intent: string; confidence: number; company?: { value?: string }; role?: { value?: string }; applicationDate?: { value?: string }; contact?: { value?: string }; missingFields: string[] } };
export type GmailReviewDecision = { decision: "ACCEPT" | "CORRECT" | "DISMISS"; company?: string; role?: string };

export function GmailReviewQueue({ items, savingId, onDecision }: { items: GmailReviewItem[]; savingId: string | null; onDecision: (id: string, payload: GmailReviewDecision) => void }) {
  return h("section", { className: "section-card review-card gmail-review-queue", "aria-labelledby": "review-heading" }, h("div", { className: "section-head" }, h("div", null, h("span", { className: "section-overline" }, "Evidence inbox"), h("h2", { id: "review-heading", className: "section-title" }, "Needs your review"), h("p", { className: "section-caption" }, "Suggestions stay out of your timeline until you confirm them.")), h("span", { className: "count-pill" }, items.length, " ", items.length === 1 ? "item" : "items")), items.length ? h("div", { className: "review-list" }, items.map((item) => h(GmailReviewCard, { key: item.suggestion.suggestionId, item, saving: savingId === item.suggestion.suggestionId, onDecision }))) : h("div", { className: "empty-state compact-empty" }, h("div", { className: "empty-icon soft", "aria-hidden": true }, "✦"), h("strong", null, "No evidence waiting"), h("span", null, "When JobFlow finds a job-related message, it will appear here before it becomes a record.")));
}

function GmailReviewCard({ item, saving, onDecision }: { item: GmailReviewItem; saving: boolean; onDecision: (id: string, payload: GmailReviewDecision) => void }) {
  const suggestion = item.suggestion; const [editing, setEditing] = useState(false); const [company, setCompany] = useState(suggestion.company?.value ?? ""); const [role, setRole] = useState(suggestion.role?.value ?? ""); const confidence = Math.round(Math.min(1, Math.max(0, suggestion.confidence)) * 100); const intent = suggestion.intent.replaceAll("_", " ").toLowerCase();
  const updateCompany = (event: ChangeEvent<HTMLInputElement>) => setCompany(event.target.value); const updateRole = (event: ChangeEvent<HTMLInputElement>) => setRole(event.target.value);
  const actions = editing ? h("button", { className: "primary-button", type: "button", disabled: saving, onClick: () => onDecision(suggestion.suggestionId, { decision: "CORRECT", company, role }) }, saving ? "Saving…" : "Save correction") : h("div", { className: "gmail-review-buttons" }, h("button", { className: "outline-button", type: "button", disabled: saving, onClick: () => onDecision(suggestion.suggestionId, { decision: "DISMISS" }) }, "Dismiss"), h("button", { className: "outline-button", type: "button", disabled: saving, onClick: () => setEditing(true) }, "Correct"), h("button", { className: "primary-button", type: "button", disabled: saving, onClick: () => onDecision(suggestion.suggestionId, { decision: "ACCEPT" }) }, saving ? "Saving…" : "Confirm"));
  return h("article", { className: "gmail-review-item" }, h("div", { className: "gmail-review-item-main" }, h("div", { className: "review-top" }, h("strong", { className: "review-name" }, suggestion.company?.value ?? "Unknown company"), h("span", { className: "confidence" }, confidence, "% confidence")), h("div", { className: "review-role" }, suggestion.role?.value ?? "Role needs confirmation", " ", h("span", { "aria-hidden": true }, "·"), " ", intent), suggestion.contact?.value && h("div", { className: "gmail-review-detail" }, "Contact: ", suggestion.contact.value), suggestion.applicationDate?.value && h("div", { className: "gmail-review-detail" }, "Date: ", suggestion.applicationDate.value), h("div", { className: "evidence" }, "JobFlow found a ", intent, " signal in your connected Gmail. ", suggestion.missingFields.length ? `Still needed: ${suggestion.missingFields.join(", ")}.` : "The suggested fields are complete."), editing && h("div", { className: "review-edit" }, h("label", null, "Company", h("input", { value: company, onChange: updateCompany })), h("label", null, "Role", h("input", { value: role, onChange: updateRole })))), h("div", { className: "review-actions" }, actions));
}
