package dev.jobflow.ingestion;

public enum MessageIntent {
    APPLICATION_CONFIRMATION,
    RECRUITER_OUTREACH,
    RECRUITER_REPLY,
    INTERVIEW_INVITATION,
    INTERVIEW_RESCHEDULE,
    INTERVIEW_FEEDBACK,
    REJECTION,
    OFFER,
    WITHDRAWAL,
    FOLLOW_UP_REQUEST,
    EMPLOYER_UPDATE,
    UNRELATED,
    UNKNOWN
}
